//
// SPDX-FileCopyrightText: 2026 R0rt1z2 <roger@r0rt1z2.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//

#pragma once

#define BOARD_NAME                      "Echo Dot 2nd Gen (2016)"
#define RECOVERY_PARTITION              "recovery"

#define HAVE_EARLY_INIT
#define HAVE_FASTBOOT_INIT
#define HAVE_FASTBOOT_CMD_REBOOT

#define FASTBOOT_INIT_PRINTF_CALL_ADDR  0x4BD21AA4

#define FB_CMD_FLASH_FUNC_ADDR          0x4BD23AFC
#define FB_CMD_ERASE_FUNC_ADDR          0x4BD23B4C
#define FB_CMD_REBOOT_FUNC_ADDR         0x4BD22130

#define FB_REGISTER_FLASH_ADDR          0x4BD21B3C
#define FB_REGISTER_ERASE_ADDR          0x4BD21B4E
#define FB_REGISTER_REBOOT_ADDR         0x4BD21B84
#define FB_REGISTER_REBOOT_BOOTLOADER_ADDR 0x4BD21B98

#define VERITY_CMDLINE_CHECK_ADDR       0x4BD2284E
#define VERITY_CMDLINE_DISABLED_ADDR    0x4BD22864

#define KERNEL_64BIT_FLAG_ADDR          0x4BD4820C
#define BOOTIMG_CMDLINE_PRINT_CALL_ADDR 0x4BD10392

#define KERNEL_CMDLINE_ADDR             0x4BD3918C
#define KERNEL_CMDLINE_SIZE             0x800
#define LK_FASTBOOT_KEY_STORE_ADDR      0x4BD21262

#define DT_RECOVERY_VERSION_LOAD_ADDR   0x4BD0D72A

#define GET_ACTIVE_SLOT_FUNC_CALLER_ADDR 0x4BD20E18
#define GET_BOOT_PART_FUNC_ADDR         0x4BD1E794
#define GET_BOOT_PART_FUNC_CALLER_ADDR  0x4BD20E1E

#define MDELAY_FUNC_ADDR                0x4BD1107C
#define THREAD_SLEEP_FUNC_ADDR          0x4BD1F70C

#define PWRAP_READ_FUNC_ADDR            0x4BD11684
#define PWRAP_WRITE_FUNC_ADDR           0x4BD11692
#define RTC_WRITEIF_UNLOCK_FUNC_ADDR    0x4BD1218E
#define RTC_WRITE_TRIGGER_FUNC_ADDR     0x4BD12174
#define MTK_DETECT_PMIC_JUST_RST_ADDR   0x4BD111BC

#define ISSI_WRITE_FUNC_ADDR            0x4BD1FCA8
#define ISSI_INIT_FUNC_ADDR             0x4BD1FD0C
#define ISSI_SET_STATE_FUNC_ADDR        0x4BD1FDDC

#define GPIO_KEY_VOLUME_UP              50
#define GPIO_KEY_VOLUME_DOWN            37
